---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'

test:
  DB_FILENAME: db/local/test.db
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'

production:
  SPOTIFY_CLIENT_ID: 'your_client_id'
  SPOTIFY_CLIENT_SECRET: 'your_client_secret'